import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { draftMode } from 'next/headers'
import { VisualEditing } from 'next-sanity/visual-editing'
import { defineQuery } from 'next-sanity'

import { MenuDesktop, MenuMobile } from '@/components/ui'
import { DisableDraftMode } from '@/components'
import { SanityLive, sanityFetch } from '@/sanity/lib/live'

const navLinksQuery = defineQuery(`*[_type == "navLink"]|order(order asc) {
			label,
			"slug": slug.current,
		 }`)

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const { data: navLinks } = await sanityFetch({ query: navLinksQuery })

	console.log((await draftMode()).isEnabled)

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary text-secondary`}>
				{/* SKIP TO MAIN CONTENT LINK - for screen readers */}
				<a
					href='#main-content'
					className='fixed top-0 left-0 z-50 -translate-y-full bg-secondary text-primary px-4 py-2 underline focus:translate-y-0'>
					Skip to main content
				</a>
				<MenuDesktop navLinks={navLinks} />
				<MenuMobile navLinks={navLinks} />
				{(await draftMode()).isEnabled && (
					<>
						<VisualEditing />
						<DisableDraftMode />
					</>
				)}
				{/* <SanityLive /> */}
				<div className='container mx-auto flex relative'>
					{/* SPACER FOR DESKTOP MENU */}
					<div className='hidden md:block flex-1/4'></div>
					{/* MAIN CONTENT */}
					{children}
				</div>
			</body>
		</html>
	)
}
